### ISSUE TITLE
Broken button: Show/Edit JSON

### ISSUE THREAD

**Issue by VA7NFH** [Photosynthesis/Timetracker#17]
In Tweak view the button `Show/Edit JSON` works once but if you try to use it again it will not work and the only way to fix it is to refresh the page.  
This happens in the web and local versions.  
Any ideas?

**Comment by VA7NFH** [comment]
I just explored the js and it seems to be that the function editjson() only sets the innerhtml of the json textarea but doesn't show it the first time around it will set the innerhtml of it and show it but the second time it just sets the innerhtml but doesn't show it. 

I think that if you add $(#json-output).show() to line 710 of timetracker.js it would fix it.

**Comment by Photosynthesis** [comment]
Thanks. Fixed in current version.
