### ISSUE TITLE
Feature request: download JSON data.

### ISSUE THREAD

**Issue by curiositry** [Photosynthesis/Timetracker#19]
There’s an option to show/edit JSON, and it would be nice to be able to download it in one click (rather than showing it and copy-pasting it into a text file.) This could be done with something like this:

```
 <a href="data:application/json;charset=utf-8,{{JSON}}" download="timetracker-data-{{DATE}}.json">Download JSON</a>
```

**Comment by Photosynthesis** [comment]
This is added. Thanks for the suggestion.

**Comment by curiositry** [comment]
Thanks. It appears that the spaces are being trimmed from the downloaded JSON. For example: 

```"name":"ThisTaskshouldhavespaces"```

The JSON displayed with "Show/Edit JSON" doesn’t have this problem.

**Comment by Photosynthesis** [comment]
You're right! It's fixed now.
