### ISSUE TITLE
In analyze view, "Total time" value resets to zero when 24+ hours have been tracked

### ISSUE THREAD

**Issue by curiositry** [Photosynthesis/Timetracker#6]
It seems that if you have tracked more than twenty-four hours on a project, the project’s "total time” at the bottom of the analyze page will start at zero again — that is, if you’ve clocked in 26hrs 41mins and 18seconds on a project, it will list the calculated total time as `02:41:18` rather than `26:41:18`.

**Comment by VA7NFH** [comment]
Photosynthesis told me yesterday that he had fixed the total time 24+ roll over error but hadn't pushed that version yet.
